source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target '${TARGET_NAME}' do
${EXPONENT_CLIENT_DEPS}

  # Unimodules
  require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
  use_unimodules!({
    modules_paths: ['../packages'],
    exclude: [
      'expo-module-template',
      'expo-bluetooth',
      'expo-in-app-purchases',
      'expo-payments-stripe',
      'expo-updates',
      # below are to be reverted
      "expo-ads-admob",
      "expo-ads-facebook",
      "expo-analytics-amplitude",
      "expo-analytics-segment",
      "expo-app-auth",
      # "expo-app-loader-provider",
      "expo-asset",
      "expo-av",
      "expo-background-fetch",
      # "expo-barcode-scanner",
      "expo-blur",
      "expo-brightness",
      "expo-battery",
      "expo-calendar",
      "expo-camera",
      "expo-camera2",
      "expo-contacts",
      "expo-crypto",
      "expo-device",
      "expo-document-picker",
      # "expo-face-detector",
      "expo-facebook",
      # "expo-file-system",
      "expo-font",
      # "expo-gl",
      # "expo-gl-cpp",
      "expo-google-sign-in",
      "expo-haptics",
      "expo-image-manipulator",
      "expo-image-picker",
      "expo-intent-launcher",
      "expo-linear-gradient",
      "expo-local-authentication",
      "expo-localization",
      "expo-location",
      "expo-mail-composer",
      "expo-media-library",
      "expo-network",
      "expo-print",
      "expo-random",
      # "expo-sensors",
      "expo-sharing",
      "expo-sms",
      "expo-speech",
      "expo-sqlite",
      # "expo-task-manager",
      "expo-video-thumbnails",
      "expo-web-browser",
      # "unimodules-barcode-scanner-interface",
      # "unimodules-camera-interface",
      # "unimodules-face-detector-interface",
      # "unimodules-sensors-interface",
      # "unimodules-task-manager-interface",
    ]
  })

${PODFILE_UNVERSIONED_RN_DEPENDENCY}
${PODFILE_VERSIONED_RN_DEPENDENCIES}

  # Build React Native with RCT_DEV enabled and RCT_ENABLE_INSPECTOR and
  # RCT_ENABLE_PACKAGER_CONNECTION disabled
  post_install do |installer|
    installer.pods_project.main_group.tab_width = '2';
    installer.pods_project.main_group.indent_width = '2';

    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
${PODFILE_VERSIONED_POSTINSTALLS}
${PODFILE_UNVERSIONED_POSTINSTALL}
    end
  end

${PODFILE_TEST_TARGET}
end
